export const allMediumArticles = [
  {
    title: "Excalidraw MCP: Turning Agent Markdown into Instant Diagrams",
    excerpt: "Ugly ASCII Workflow diagram One of the most underrated bottlenecks in technical learning and system design is visualization. We understand concepts faster when we see them, yet creating diagrams...",
    readTime: "2 min read",
    date: "Feb 18, 2026",
    url: "https://infinityai.medium.com/excalidraw-mcp-turning-agent-markdown-into-instant-diagrams-64ab8471fd67",
    tags: ["mcp-server", "excalidraw", "software-development", "claude-ai", "claude-code"]
  },
  {
    title: "Claude Code Just Ended Manual Coding for me — My Step-by-Step Guide to 3x Faster Builds in 2026",
    excerpt: "Claude Code Just Ended Manual Coding for me — My Step-by-Step Guide to 3x Faster Builds in 2026 I lost hours switching branches and fixing merge conflicts every week. Features stalled. Context...",
    readTime: "1 min read",
    date: "Feb 9, 2026",
    url: "https://infinityai.medium.com/claude-code-just-ended-manual-coding-for-me-my-step-by-step-guide-to-3x-faster-builds-in-2026-f7f2abe8f611",
    tags: ["productivity-hacks", "anthropic-claude", "claude-code", "clawdbot", "openclaw"]
  },
  {
    title: "Think You Know RAG? Take This 16-Point Checklist and Prove It Wrong",
    excerpt: "The RAG Checklist That Exposes Your 10-Line Pipeline 𝗬𝗼𝘂 𝗱𝗼𝗻’𝘁 𝗸𝗻𝗼𝘄 𝗥𝗔𝗚!! Just because you connected Embeddings → VectorDB → Query → Result, doesn’t mean you “know RAG.” That’s not...",
    readTime: "2 min read",
    date: "Oct 12, 2025",
    url: "https://infinityai.medium.com/think-you-know-rag-take-this-16-point-checklist-and-prove-it-wrong-4fe75c0448bc",
    tags: ["rags", "top-5", "llamaparse", "how-to-parse-pdf", "generative-ai-tools"]
  },
  {
    title: "Fix RAG Hallucinations at the Source: Top PDF Parsers Ranked 2025",
    excerpt: "This is your Data, yes, Garbage. If you’re still relying on PyPDF / PyMuPDF / pdfplumber for parsing, your RAG pipeline is already broken at the data layer . No matter how advanced your workflow is...",
    readTime: "5 min read",
    date: "Sep 5, 2025",
    url: "https://infinityai.medium.com/3-proven-techniques-to-accurately-parse-your-pdfs-2c01c5badb84",
    tags: ["generative-ai", "parsing-techniques", "agentic-ai", "retrieval-augmented-gen", "artificial-intelligence"]
  },
  {
    title: "How to Create Your Personal AI Agent [ Part-2 ]",
    excerpt: "Read till the end to watch the Video of your Personal Agent 😎 If you haven’t read Part 1, I strongly recommend you read that first and then come here: Part-1 Now, let’s understand what we will need...",
    readTime: "4 min read",
    date: "Jan 16, 2025",
    url: "https://infinityai.medium.com/how-to-create-your-personal-ai-agent-part-2-a28729b6f8c7",
    tags: ["how-to", "ai-agent", "llm", "ai", "create"]
  },
  {
    title: "How to Create Your First Personal AI Agent For Beginners [ Part-1 ]",
    excerpt: "Ever wondered if there should be a personal agent that has all your information? No worries, you can build one right here! 😉 First Lets Understand, what is AI agent ? An AI agent is a software...",
    readTime: "3 min read",
    date: "Jan 16, 2025",
    url: "https://infinityai.medium.com/how-to-create-your-personal-ai-agent-part-1-1a6423966911",
    tags: ["how-to-create-ai-agent", "phidata", "agents", "llm", "ai-agent"]
  },
  {
    title: "How To Run llama3, phi3 on your Local PC Using Ollama",
    excerpt: "If you want to use Large Language Models on your Local Environment then, Ollama is For You, My Friend !! Read till the end, there’s a surprise for you !!!! 🤩🥳🥳 If you are Facing the Connection...",
    readTime: "8 min read",
    date: "Nov 3, 2024",
    url: "https://infinityai.medium.com/how-to-run-llama3-phi3-on-your-local-pc-using-ollama-b84213b2960a",
    tags: ["llama-3", "llm", "google-colab", "local-pc", "ollama"]
  },
  {
    title: "Ollama ConnectError: [Errno 99] Cannot assign requested address",
    excerpt: "Ever Faced this Error while Using Ollama ?? ConnectError: [Errno 99] Cannot assign requested address Fed up with this Error ? And Don’t Know what to do ? Then you are at the Right Place. I got you...",
    readTime: "8 min read",
    date: "Oct 29, 2024",
    url: "https://infinityai.medium.com/ollama-connecterror-errno-99-cannot-assign-requested-address-f0facad8027a",
    tags: ["large-language-models", "ollama", "error", "llm", "ollama-connecterror"]
  },
  {
    title: "No Coding Required! — Create a Powerful Chatbot on Google Cloud’s Vertex AI",
    excerpt: "No Coding Required! — Create a Powerful Chatbot on Google Cloud’s Vertex AI Generated by Gemini There are Multiple ways to Create a ChatBot without code/Low Code and today we will Look into the...",
    readTime: "5 min read",
    date: "Oct 25, 2024",
    url: "https://infinityai.medium.com/no-coding-required-create-a-powerful-chatbot-on-google-clouds-vertex-ai-a82a2e503094",
    tags: ["google-cloud-platform", "generative-ai-tools", "no-code", "chatbots", "chatgpt"]
  },
  {
    title: "20 Lines of Code To Generate Messages Using OpenAI API",
    excerpt: "We have already configured the OpenAI API key. If you require instructions on setting up an API key, please refer to the provided Blog . Generated by ChatGPT Step 1: To use a GPT model via the...",
    readTime: "2 min read",
    date: "Oct 22, 2024",
    url: "https://infinityai.medium.com/20-lines-of-code-to-generate-messages-using-openai-api-36f8ae44142a",
    tags: ["chatgpt", "openai-chatgpt", "messaging", "chatbots", "openai"]
  }
];
